// <auto-generated />
using System;
using CooperativaApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CooperativaApp.Migrations
{
    [DbContext(typeof(CooperativaContext))]
    [Migration("20260217054432_FixRelacionesDetallePago")]
    partial class FixRelacionesDetallePago
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CooperativaApp.Models.AsientoContable", b =>
                {
                    b.Property<int>("IdAsiento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdAsiento"));

                    b.Property<string>("CuentaDebe")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CuentaHaber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Monto")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ReferenciaId")
                        .HasColumnType("int");

                    b.Property<string>("TipoOperacion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdAsiento");

                    b.ToTable("AsientosContables");
                });

            modelBuilder.Entity("CooperativaApp.Models.ConfiguracionMora", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IdConfiguracion");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<int>("DiasGracia")
                        .HasColumnType("int");

                    b.Property<decimal?>("MontoFijo")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Tasa")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("TipoMora");

                    b.Property<string>("TipoAplicacion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ConfiguracionMora");
                });

            modelBuilder.Entity("CooperativaApp.Models.Credito", b =>
                {
                    b.Property<int>("IdCredito")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCredito"));

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("FechaAprobacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaSolicitud")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdSocio")
                        .HasColumnType("int");

                    b.Property<decimal>("Monto")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("PlazoMeses")
                        .HasColumnType("int");

                    b.Property<decimal>("SaldoCapital")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TasaInteres")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TipoCalculo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdCredito");

                    b.ToTable("Credito");
                });

            modelBuilder.Entity("CooperativaApp.Models.Cuota", b =>
                {
                    b.Property<int>("IdCuota")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCuota"));

                    b.Property<decimal>("Capital")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Estado")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaVencimiento")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdCredito")
                        .HasColumnType("int");

                    b.Property<decimal>("Interes")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MontoCuota")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("NumeroCuota")
                        .HasColumnType("int");

                    b.Property<decimal>("Saldo")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SaldoCapital")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SaldoInteres")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("IdCuota");

                    b.HasIndex("IdCredito");

                    b.ToTable("Cuota");
                });

            modelBuilder.Entity("CooperativaApp.Models.Mora", b =>
                {
                    b.Property<int>("IdMora")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdMora"));

                    b.Property<int?>("CuotaIdCuota")
                        .HasColumnType("int");

                    b.Property<int?>("DiasMora")
                        .HasColumnType("int");

                    b.Property<string>("Estado")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("FechaFin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaGeneracion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdCuota")
                        .HasColumnType("int");

                    b.Property<decimal>("MontoMora")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("MontoPagado")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("SaldoMora")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("IdMora");

                    b.HasIndex("CuotaIdCuota");

                    b.ToTable("Moras");
                });

            modelBuilder.Entity("CooperativaApp.Models.Pago", b =>
                {
                    b.Property<int>("IdPago")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPago"));

                    b.Property<DateTime>("FechaPago")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdCredito")
                        .HasColumnType("int");

                    b.Property<decimal>("MontoPagado")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("IdPago");

                    b.ToTable("Pago");
                });

            modelBuilder.Entity("CooperativaApp.Models.Socio", b =>
                {
                    b.Property<int>("IdSocio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IdSocio");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdSocio"));

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DNI")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdSocio");

                    b.ToTable("Socio");
                });

            modelBuilder.Entity("DetallePago", b =>
                {
                    b.Property<int>("IdDetallePago")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDetallePago"));

                    b.Property<decimal>("CapitalPagado")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<int?>("IdCuota")
                        .HasColumnType("int");

                    b.Property<int?>("IdMora")
                        .HasColumnType("int");

                    b.Property<int>("IdPago")
                        .HasColumnType("int");

                    b.Property<decimal>("InteresPagado")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("MoraIdMora")
                        .HasColumnType("int");

                    b.Property<decimal>("MoraPagada")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("PagoIdPago")
                        .HasColumnType("int");

                    b.HasKey("IdDetallePago");

                    b.HasIndex("IdCuota");

                    b.HasIndex("IdMora");

                    b.HasIndex("IdPago");

                    b.HasIndex("MoraIdMora");

                    b.HasIndex("PagoIdPago");

                    b.ToTable("DetallePago");
                });

            modelBuilder.Entity("CooperativaApp.Models.Cuota", b =>
                {
                    b.HasOne("CooperativaApp.Models.Credito", "Credito")
                        .WithMany("Cuotas")
                        .HasForeignKey("IdCredito")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Credito");
                });

            modelBuilder.Entity("CooperativaApp.Models.Mora", b =>
                {
                    b.HasOne("CooperativaApp.Models.Cuota", "Cuota")
                        .WithMany("Moras")
                        .HasForeignKey("CuotaIdCuota");

                    b.Navigation("Cuota");
                });

            modelBuilder.Entity("DetallePago", b =>
                {
                    b.HasOne("CooperativaApp.Models.Cuota", "Cuota")
                        .WithMany()
                        .HasForeignKey("IdCuota")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CooperativaApp.Models.Mora", "Mora")
                        .WithMany()
                        .HasForeignKey("IdMora")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CooperativaApp.Models.Pago", "Pago")
                        .WithMany()
                        .HasForeignKey("IdPago")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CooperativaApp.Models.Mora", null)
                        .WithMany("Detalles")
                        .HasForeignKey("MoraIdMora");

                    b.HasOne("CooperativaApp.Models.Pago", null)
                        .WithMany("Detalles")
                        .HasForeignKey("PagoIdPago");

                    b.Navigation("Cuota");

                    b.Navigation("Mora");

                    b.Navigation("Pago");
                });

            modelBuilder.Entity("CooperativaApp.Models.Credito", b =>
                {
                    b.Navigation("Cuotas");
                });

            modelBuilder.Entity("CooperativaApp.Models.Cuota", b =>
                {
                    b.Navigation("Moras");
                });

            modelBuilder.Entity("CooperativaApp.Models.Mora", b =>
                {
                    b.Navigation("Detalles");
                });

            modelBuilder.Entity("CooperativaApp.Models.Pago", b =>
                {
                    b.Navigation("Detalles");
                });
#pragma warning restore 612, 618
        }
    }
}
