// <auto-generated />
using System;
using CooperativaApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CooperativaApp.Migrations
{
    [DbContext(typeof(CooperativaContext))]
    partial class CooperativaContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CooperativaApp.DTOS.AprobacionResponse", b =>
                {
                    b.Property<bool>("Exito")
                        .HasColumnType("bit");

                    b.Property<int>("IdCreditoGenerado")
                        .HasColumnType("int");

                    b.Property<string>("Mensaje")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("AprobacionResponse");
                });

            modelBuilder.Entity("CooperativaApp.DTOS.CuotaAnaliticaDTO", b =>
                {
                    b.Property<decimal>("Capital")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("FechaUltimoPago")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaVencimiento")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Interes")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("MedioPago")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("MontoCuota")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MontoEnRevision")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("NumeroCuota")
                        .HasColumnType("int");

                    b.Property<decimal>("PagoCapital")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PagoInteres")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PagoMora")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SaldoCapital")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SaldoInteres")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SaldoMora")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SaldoTotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalPagado")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.ToTable((string)null);

                    b.ToView(null, (string)null);
                });

            modelBuilder.Entity("CooperativaApp.DTOS.CuotaDetalleDTO", b =>
                {
                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("FechaPago")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaSolicitud")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaVencimiento")
                        .HasColumnType("datetime2");

                    b.Property<string>("MedioPagoReal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MedioRevision")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("MontoCuota")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MontoEnRevision")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MontoPagadoReal")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("NumeroCuota")
                        .HasColumnType("int");

                    b.Property<decimal?>("SaldoCapital")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SaldoCuota")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.ToTable((string)null);

                    b.ToView(null, (string)null);
                });

            modelBuilder.Entity("CooperativaApp.DTOS.OperacionResponse", b =>
                {
                    b.Property<bool>("Exito")
                        .HasColumnType("bit")
                        .HasJsonPropertyName("exito");

                    b.Property<int?>("IdCredito")
                        .HasColumnType("int")
                        .HasJsonPropertyName("idCredito");

                    b.Property<int?>("IdMovimientoCaja")
                        .HasColumnType("int")
                        .HasJsonPropertyName("idMovimientoCaja");

                    b.Property<int?>("IdOperacion")
                        .HasColumnType("int")
                        .HasJsonPropertyName("idOperacion");

                    b.Property<int?>("IdPago")
                        .HasColumnType("int")
                        .HasJsonPropertyName("idPago");

                    b.Property<string>("Mensaje")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasJsonPropertyName("mensaje");

                    b.Property<decimal?>("SaldoPendienteDesembolso")
                        .HasColumnType("decimal(18,2)")
                        .HasJsonPropertyName("saldoPendienteDesembolso");

                    b.ToTable("OperacionResponses");
                });

            modelBuilder.Entity("CooperativaApp.Models.AporteSocio", b =>
                {
                    b.Property<int>("IdAporte")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdAporte"));

                    b.Property<int>("AnioAportado")
                        .HasColumnType("int");

                    b.Property<int>("CantidadAcciones")
                        .HasColumnType("int");

                    b.Property<string>("ComentarioCaja")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EstadoPago")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.Property<DateTime>("FechaPago")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaValidacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdConfig")
                        .HasColumnType("int");

                    b.Property<int?>("IdMedioPago")
                        .HasColumnType("int");

                    b.Property<int?>("IdMovimientoCaja")
                        .HasColumnType("int");

                    b.Property<int>("IdSocio")
                        .HasColumnType("int");

                    b.Property<int>("IdUsuarioRegistro")
                        .HasColumnType("int");

                    b.Property<int?>("IdUsuarioValidador")
                        .HasColumnType("int");

                    b.Property<int>("MesAportado")
                        .HasColumnType("int");

                    b.Property<decimal>("MontoPagado")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("UrlEvidencia")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdAporte");

                    b.HasIndex("IdConfig");

                    b.HasIndex("IdMedioPago");

                    b.HasIndex("IdSocio", "MesAportado", "AnioAportado")
                        .IsUnique();

                    b.ToTable("AportesSocios", (string)null);
                });

            modelBuilder.Entity("CooperativaApp.Models.AsientosContables", b =>
                {
                    b.Property<int>("IdAsiento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdAsiento"));

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<string>("Glosa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("IdReferencia")
                        .HasColumnType("int");

                    b.Property<string>("Origen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdAsiento");

                    b.ToTable("AsientosContables");
                });

            modelBuilder.Entity("CooperativaApp.Models.ConceptoOperacion", b =>
                {
                    b.Property<int>("IdConcepto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdConcepto"));

                    b.Property<string>("CuentaContableDebe")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("CuentaContableHaber")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipoMovimiento")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdConcepto");

                    b.HasIndex("CuentaContableDebe");

                    b.HasIndex("CuentaContableHaber");

                    b.ToTable("ConceptosOperacion", (string)null);
                });

            modelBuilder.Entity("CooperativaApp.Models.ConfigAporte", b =>
                {
                    b.Property<int>("IdConfig")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdConfig"));

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("FechaFin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdUsuarioRegistro")
                        .HasColumnType("int");

                    b.Property<decimal>("ValorAccion")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("IdConfig");

                    b.ToTable("ConfigAportes", (string)null);
                });

            modelBuilder.Entity("CooperativaApp.Models.ConfiguracionMora", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IdConfiguracion");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<int>("DiasGracia")
                        .HasColumnType("int");

                    b.Property<decimal?>("MontoFijo")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Tasa")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("TipoMora");

                    b.Property<string>("TipoAplicacion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ConfiguracionMora");
                });

            modelBuilder.Entity("CooperativaApp.Models.Credito", b =>
                {
                    b.Property<int>("IdCredito")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCredito"));

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EstadoCredito")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("FechaAprobacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaDesembolso")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaSolicitud")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdSocio")
                        .HasColumnType("int");

                    b.Property<decimal>("Monto")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("MontoDesembolsado")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("PlazoMeses")
                        .HasColumnType("int");

                    b.Property<decimal>("SaldoCapital")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TasaInteres")
                        .HasPrecision(8, 4)
                        .HasColumnType("decimal(8,4)");

                    b.Property<string>("TipoCalculo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdCredito");

                    b.HasIndex("IdSocio");

                    b.ToTable("Credito");
                });

            modelBuilder.Entity("CooperativaApp.Models.Cuota", b =>
                {
                    b.Property<int>("IdCuota")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCuota"));

                    b.Property<decimal>("Capital")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Estado")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaVencimiento")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdCredito")
                        .HasColumnType("int");

                    b.Property<decimal>("Interes")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MontoCuota")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("NumeroCuota")
                        .HasColumnType("int");

                    b.Property<decimal>("Saldo")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SaldoCapital")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SaldoInteres")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("IdCuota");

                    b.HasIndex("IdCredito");

                    b.ToTable("Cuota");
                });

            modelBuilder.Entity("CooperativaApp.Models.DetalleAsiento", b =>
                {
                    b.Property<int>("IdDetalle")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDetalle"));

                    b.Property<string>("CuentaContable")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Debe")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Haber")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("IdAsiento")
                        .HasColumnType("int");

                    b.HasKey("IdDetalle");

                    b.HasIndex("IdAsiento");

                    b.ToTable("DetalleAsiento");
                });

            modelBuilder.Entity("CooperativaApp.Models.DetallePago", b =>
                {
                    b.Property<int>("IdDetallePago")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IdPagoDetalle");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDetallePago"));

                    b.Property<int>("IdConcepto")
                        .HasColumnType("int")
                        .HasColumnName("IdConcepto");

                    b.Property<int>("IdCuota")
                        .HasColumnType("int")
                        .HasColumnName("IdCuota");

                    b.Property<int>("IdPago")
                        .HasColumnType("int")
                        .HasColumnName("IdPago");

                    b.Property<decimal>("Monto")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("Monto");

                    b.Property<int?>("MoraIdMora")
                        .HasColumnType("int");

                    b.HasKey("IdDetallePago");

                    b.HasIndex("IdCuota");

                    b.HasIndex("IdPago");

                    b.HasIndex("MoraIdMora");

                    b.ToTable("PagosDetalle");
                });

            modelBuilder.Entity("CooperativaApp.Models.Familiaridad", b =>
                {
                    b.Property<int>("IdFamiliaridad")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdFamiliaridad"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaVinculacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdParentesco")
                        .HasColumnType("int");

                    b.Property<int>("IdSocioFamiliar")
                        .HasColumnType("int");

                    b.Property<int>("IdSocioTitular")
                        .HasColumnType("int");

                    b.HasKey("IdFamiliaridad");

                    b.HasIndex("IdParentesco");

                    b.HasIndex("IdSocioFamiliar");

                    b.HasIndex("IdSocioTitular");

                    b.ToTable("Familiaridad", (string)null);
                });

            modelBuilder.Entity("CooperativaApp.Models.GlobalSettings", b =>
                {
                    b.Property<int>("SettingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SettingId"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DataType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsSystem")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("SettingKey")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("SettingValue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.HasKey("SettingId");

                    b.ToTable("GlobalSettings");
                });

            modelBuilder.Entity("CooperativaApp.Models.HistorialEstadoSocio", b =>
                {
                    b.Property<int>("IdHistorial")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdHistorial"));

                    b.Property<string>("Comentario")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("EstadoAnterior")
                        .HasColumnType("bit");

                    b.Property<bool?>("EstadoNuevo")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaAccion")
                        .HasColumnType("datetime2");

                    b.Property<int?>("IdMotivo")
                        .HasColumnType("int");

                    b.Property<int>("IdSocio")
                        .HasColumnType("int");

                    b.Property<int>("IdUsuarioAccion")
                        .HasColumnType("int");

                    b.HasKey("IdHistorial");

                    b.HasIndex("IdMotivo");

                    b.HasIndex("IdSocio");

                    b.ToTable("HistorialEstadoSocio", (string)null);
                });

            modelBuilder.Entity("CooperativaApp.Models.LogActividad", b =>
                {
                    b.Property<long>("IdLog")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("IdLog"));

                    b.Property<string>("Accion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Detalle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<string>("IP")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("IdUsuario")
                        .HasColumnType("int");

                    b.HasKey("IdLog");

                    b.ToTable("Logs_Actividad", (string)null);
                });

            modelBuilder.Entity("CooperativaApp.Models.MedioPago", b =>
                {
                    b.Property<int>("IdMedioPago")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdMedioPago"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdMedioPago");

                    b.ToTable("MediosPago");
                });

            modelBuilder.Entity("CooperativaApp.Models.Modulo", b =>
                {
                    b.Property<int>("IdModulo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdModulo"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Icono")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Orden")
                        .HasColumnType("int");

                    b.Property<string>("Ruta")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdModulo");

                    b.ToTable("Modulos");
                });

            modelBuilder.Entity("CooperativaApp.Models.Mora", b =>
                {
                    b.Property<int>("IdMora")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdMora"));

                    b.Property<int?>("CuotaIdCuota")
                        .HasColumnType("int");

                    b.Property<int?>("DiasMora")
                        .HasColumnType("int");

                    b.Property<string>("Estado")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("FechaFin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaGeneracion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdCuota")
                        .HasColumnType("int");

                    b.Property<decimal>("MontoMora")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("MontoPagado")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("SaldoMora")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("IdMora");

                    b.HasIndex("CuotaIdCuota");

                    b.ToTable("Moras");
                });

            modelBuilder.Entity("CooperativaApp.Models.MotivoBaja", b =>
                {
                    b.Property<int>("IdMotivo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdMotivo"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("RequiereComentario")
                        .HasColumnType("bit");

                    b.HasKey("IdMotivo");

                    b.ToTable("MotivosBaja", (string)null);
                });

            modelBuilder.Entity("CooperativaApp.Models.MovimientoCaja", b =>
                {
                    b.Property<int>("IdMovimiento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdMovimiento"));

                    b.Property<string>("Estado")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<int?>("IdAsiento")
                        .HasColumnType("int");

                    b.Property<int?>("IdCaja")
                        .HasColumnType("int");

                    b.Property<int>("IdConcepto")
                        .HasColumnType("int");

                    b.Property<int?>("IdCredito")
                        .HasColumnType("int");

                    b.Property<int?>("IdMedioPago")
                        .HasColumnType("int");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int");

                    b.Property<decimal>("Monto")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("IdMovimiento");

                    b.HasIndex("IdConcepto");

                    b.ToTable("MovimientosCaja");
                });

            modelBuilder.Entity("CooperativaApp.Models.Opcion", b =>
                {
                    b.Property<int>("IdOpcion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdOpcion"));

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<string>("Icono")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Modulo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PerfilIdPerfil")
                        .HasColumnType("int");

                    b.Property<string>("Url")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdOpcion");

                    b.HasIndex("PerfilIdPerfil");

                    b.ToTable("Opciones", (string)null);
                });

            modelBuilder.Entity("CooperativaApp.Models.Pago", b =>
                {
                    b.Property<int>("IdPago")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPago"));

                    b.Property<DateTime>("FechaPago")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdCredito")
                        .HasColumnType("int");

                    b.Property<int?>("IdMedioPago")
                        .HasColumnType("int");

                    b.Property<int>("IdSocio")
                        .HasColumnType("int");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int");

                    b.Property<decimal>("MontoTotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("NroOperacion")
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdPago");

                    b.HasIndex("IdCredito");

                    b.HasIndex("IdMedioPago");

                    b.ToTable("Pagos", (string)null);
                });

            modelBuilder.Entity("CooperativaApp.Models.Parentesco", b =>
                {
                    b.Property<int>("IdParentesco")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdParentesco"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdParentesco");

                    b.ToTable("Parentesco");
                });

            modelBuilder.Entity("CooperativaApp.Models.Perfil", b =>
                {
                    b.Property<int>("IdPerfil")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPerfil"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdPerfil");

                    b.ToTable("Perfiles", (string)null);
                });

            modelBuilder.Entity("CooperativaApp.Models.PerfilModulo", b =>
                {
                    b.Property<int>("IdPerfil")
                        .HasColumnType("int");

                    b.Property<int>("IdModulo")
                        .HasColumnType("int");

                    b.HasKey("IdPerfil", "IdModulo");

                    b.HasIndex("IdModulo");

                    b.ToTable("PerfilModulo");
                });

            modelBuilder.Entity("CooperativaApp.Models.Producto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("PRO_Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CalculoCuota")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("PRO_CALCULOCUOTA");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("PRO_Descripcion");

                    b.Property<bool?>("Estado")
                        .HasColumnType("bit")
                        .HasColumnName("PRO_Estado");

                    b.Property<string>("Nombre")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("PRO_Nombre");

                    b.Property<decimal?>("TasaReferencial")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("PRO_TasaReferencial");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("int")
                        .HasColumnName("PRO_Usuario");

                    b.HasKey("Id");

                    b.ToTable("PRODUCTO");
                });

            modelBuilder.Entity("CooperativaApp.Models.ProductoTasa", b =>
                {
                    b.Property<int>("IdTasa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTasa"));

                    b.Property<decimal>("MontoMaximo")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("MontoMinimo")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("ProductoId")
                        .HasColumnType("int")
                        .HasColumnName("PRO_Id");

                    b.Property<decimal>("TasaInteres")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5, 2)");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("int")
                        .HasColumnName("PROTA_Usuario");

                    b.HasKey("IdTasa");

                    b.HasIndex("ProductoId");

                    b.ToTable("ProductoTasas");
                });

            modelBuilder.Entity("CooperativaApp.Models.Socio", b =>
                {
                    b.Property<int>("IdSocio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IdSocio");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdSocio"));

                    b.Property<string>("ApellidoMaterno")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ApellidoPaterno")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DNI")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("Direccion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaNacimiento")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<int?>("IdUsuarioModificacion")
                        .HasColumnType("int");

                    b.Property<int?>("IdUsuarioRegistro")
                        .HasColumnType("int");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefono")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("correo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdSocio");

                    b.ToTable("Socio", (string)null);
                });

            modelBuilder.Entity("CooperativaApp.Models.SolicitudCredito", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ComentarioEvaluador")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Estado")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("FechaCreacion")
                        .HasColumnType("datetime2")
                        .HasColumnName("FechaRegistro");

                    b.Property<DateTime?>("FechaEvaluacion")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("MontoSolicitado")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Observaciones")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PlazoMeses")
                        .HasColumnType("int")
                        .HasColumnName("PlazoSolicitado");

                    b.Property<int>("ProductoId")
                        .HasColumnType("int");

                    b.Property<int>("SocioId")
                        .HasColumnType("int");

                    b.Property<decimal>("TasaAplicada")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("TasaPropuesta");

                    b.Property<int?>("UsuarioCreadorId")
                        .HasColumnType("int");

                    b.Property<int?>("UsuarioEvaluador")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductoId");

                    b.HasIndex("SocioId");

                    b.ToTable("Solicitudes", "dbo");
                });

            modelBuilder.Entity("CooperativaApp.Models.SolicitudPagoDetalle", b =>
                {
                    b.Property<int>("IdSolicitudDetalle")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdSolicitudDetalle"));

                    b.Property<decimal>("CapitalCubierto")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("FechaSolicitud")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdCuota")
                        .HasColumnType("int");

                    b.Property<int>("IdSolicitud")
                        .HasColumnType("int");

                    b.Property<decimal>("InteresCubierto")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MontoAplicado")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("IdSolicitudDetalle");

                    b.HasIndex("IdCuota");

                    b.HasIndex("IdSolicitud");

                    b.ToTable("SolicitudPagoDetalle", (string)null);
                });

            modelBuilder.Entity("CooperativaApp.Models.SolicitudPagoSocio", b =>
                {
                    b.Property<int>("IdSolicitud")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdSolicitud"));

                    b.Property<string>("ComprobanteUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("FechaProcesamiento")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaSolicitud")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdCredito")
                        .HasColumnType("int");

                    b.Property<int>("IdEstado")
                        .HasColumnType("int");

                    b.Property<int>("IdSocio")
                        .HasColumnType("int");

                    b.Property<int?>("IdUsuarioCajero")
                        .HasColumnType("int");

                    b.Property<string>("MedioPago")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Monto")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ObservacionesCajero")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReferenciaOperacion")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdSolicitud");

                    b.HasIndex("IdCredito");

                    b.HasIndex("IdSocio");

                    b.ToTable("SolicitudPagoSocio");
                });

            modelBuilder.Entity("CooperativaApp.Models.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUsuario"));

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdPerfil")
                        .HasColumnType("int");

                    b.Property<int?>("IdSocio")
                        .HasColumnType("int");

                    b.Property<int>("IntentosFallidos")
                        .HasColumnType("int");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("bit");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<bool>("RequiereCambioPassword")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UltimoAcceso")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UltimoLogin")
                        .HasColumnType("datetime2");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdUsuario");

                    b.HasIndex("IdPerfil");

                    b.HasIndex("IdSocio");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("YourProject.Models.CuentaContable", b =>
                {
                    b.Property<string>("CodigoCuenta")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool>("Activa")
                        .HasColumnType("bit");

                    b.Property<string>("CodigoCuentaPadre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EsAnalitica")
                        .HasColumnType("bit");

                    b.Property<string>("Naturaleza")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<int>("Nivel")
                        .HasColumnType("int");

                    b.Property<string>("NombreCuenta")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("CodigoCuenta");

                    b.ToTable("CuentasContables");
                });

            modelBuilder.Entity("CooperativaApp.Models.AporteSocio", b =>
                {
                    b.HasOne("CooperativaApp.Models.ConfigAporte", "ConfigAporte")
                        .WithMany()
                        .HasForeignKey("IdConfig")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CooperativaApp.Models.MedioPago", "MedioPago")
                        .WithMany()
                        .HasForeignKey("IdMedioPago");

                    b.HasOne("CooperativaApp.Models.Socio", "Socio")
                        .WithMany()
                        .HasForeignKey("IdSocio")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ConfigAporte");

                    b.Navigation("MedioPago");

                    b.Navigation("Socio");
                });

            modelBuilder.Entity("CooperativaApp.Models.ConceptoOperacion", b =>
                {
                    b.HasOne("YourProject.Models.CuentaContable", "CuentaContableDebeNavigation")
                        .WithMany()
                        .HasForeignKey("CuentaContableDebe")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("YourProject.Models.CuentaContable", "CuentaContableHaberNavigation")
                        .WithMany()
                        .HasForeignKey("CuentaContableHaber")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("CuentaContableDebeNavigation");

                    b.Navigation("CuentaContableHaberNavigation");
                });

            modelBuilder.Entity("CooperativaApp.Models.Credito", b =>
                {
                    b.HasOne("CooperativaApp.Models.Socio", "Socio")
                        .WithMany()
                        .HasForeignKey("IdSocio")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Socio");
                });

            modelBuilder.Entity("CooperativaApp.Models.Cuota", b =>
                {
                    b.HasOne("CooperativaApp.Models.Credito", "Credito")
                        .WithMany("Cuotas")
                        .HasForeignKey("IdCredito")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Credito");
                });

            modelBuilder.Entity("CooperativaApp.Models.DetalleAsiento", b =>
                {
                    b.HasOne("CooperativaApp.Models.AsientosContables", "Asiento")
                        .WithMany("Detalles")
                        .HasForeignKey("IdAsiento")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Asiento");
                });

            modelBuilder.Entity("CooperativaApp.Models.DetallePago", b =>
                {
                    b.HasOne("CooperativaApp.Models.Cuota", "Cuota")
                        .WithMany("PagosDetalle")
                        .HasForeignKey("IdCuota")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CooperativaApp.Models.Pago", "Pago")
                        .WithMany()
                        .HasForeignKey("IdPago")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CooperativaApp.Models.Mora", null)
                        .WithMany("Detalles")
                        .HasForeignKey("MoraIdMora");

                    b.Navigation("Cuota");

                    b.Navigation("Pago");
                });

            modelBuilder.Entity("CooperativaApp.Models.Familiaridad", b =>
                {
                    b.HasOne("CooperativaApp.Models.Parentesco", "Parentesco")
                        .WithMany("Familiaridades")
                        .HasForeignKey("IdParentesco")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CooperativaApp.Models.Socio", "SocioFamiliar")
                        .WithMany()
                        .HasForeignKey("IdSocioFamiliar")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CooperativaApp.Models.Socio", "SocioTitular")
                        .WithMany()
                        .HasForeignKey("IdSocioTitular")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Parentesco");

                    b.Navigation("SocioFamiliar");

                    b.Navigation("SocioTitular");
                });

            modelBuilder.Entity("CooperativaApp.Models.HistorialEstadoSocio", b =>
                {
                    b.HasOne("CooperativaApp.Models.MotivoBaja", "Motivo")
                        .WithMany()
                        .HasForeignKey("IdMotivo")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CooperativaApp.Models.Socio", "Socio")
                        .WithMany("HistorialEstados")
                        .HasForeignKey("IdSocio")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Motivo");

                    b.Navigation("Socio");
                });

            modelBuilder.Entity("CooperativaApp.Models.Mora", b =>
                {
                    b.HasOne("CooperativaApp.Models.Cuota", "Cuota")
                        .WithMany("Moras")
                        .HasForeignKey("CuotaIdCuota");

                    b.Navigation("Cuota");
                });

            modelBuilder.Entity("CooperativaApp.Models.MovimientoCaja", b =>
                {
                    b.HasOne("CooperativaApp.Models.ConceptoOperacion", "Concepto")
                        .WithMany()
                        .HasForeignKey("IdConcepto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Concepto");
                });

            modelBuilder.Entity("CooperativaApp.Models.Opcion", b =>
                {
                    b.HasOne("CooperativaApp.Models.Perfil", null)
                        .WithMany("Opciones")
                        .HasForeignKey("PerfilIdPerfil");
                });

            modelBuilder.Entity("CooperativaApp.Models.Pago", b =>
                {
                    b.HasOne("CooperativaApp.Models.Credito", "Credito")
                        .WithMany()
                        .HasForeignKey("IdCredito")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("CooperativaApp.Models.MedioPago", "MedioPago")
                        .WithMany()
                        .HasForeignKey("IdMedioPago");

                    b.Navigation("Credito");

                    b.Navigation("MedioPago");
                });

            modelBuilder.Entity("CooperativaApp.Models.PerfilModulo", b =>
                {
                    b.HasOne("CooperativaApp.Models.Modulo", "Modulo")
                        .WithMany()
                        .HasForeignKey("IdModulo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Modulo");
                });

            modelBuilder.Entity("CooperativaApp.Models.ProductoTasa", b =>
                {
                    b.HasOne("CooperativaApp.Models.Producto", "Producto")
                        .WithMany("Tasas")
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("CooperativaApp.Models.SolicitudCredito", b =>
                {
                    b.HasOne("CooperativaApp.Models.Producto", "Producto")
                        .WithMany()
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CooperativaApp.Models.Socio", "Socio")
                        .WithMany()
                        .HasForeignKey("SocioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Producto");

                    b.Navigation("Socio");
                });

            modelBuilder.Entity("CooperativaApp.Models.SolicitudPagoDetalle", b =>
                {
                    b.HasOne("CooperativaApp.Models.Cuota", "Cuota")
                        .WithMany()
                        .HasForeignKey("IdCuota")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("CooperativaApp.Models.SolicitudPagoSocio", "Solicitud")
                        .WithMany()
                        .HasForeignKey("IdSolicitud")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Cuota");

                    b.Navigation("Solicitud");
                });

            modelBuilder.Entity("CooperativaApp.Models.SolicitudPagoSocio", b =>
                {
                    b.HasOne("CooperativaApp.Models.Credito", "Credito")
                        .WithMany()
                        .HasForeignKey("IdCredito")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CooperativaApp.Models.Socio", "Socio")
                        .WithMany()
                        .HasForeignKey("IdSocio")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Credito");

                    b.Navigation("Socio");
                });

            modelBuilder.Entity("CooperativaApp.Models.Usuario", b =>
                {
                    b.HasOne("CooperativaApp.Models.Perfil", "Perfil")
                        .WithMany()
                        .HasForeignKey("IdPerfil")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CooperativaApp.Models.Socio", "Socio")
                        .WithMany()
                        .HasForeignKey("IdSocio");

                    b.Navigation("Perfil");

                    b.Navigation("Socio");
                });

            modelBuilder.Entity("CooperativaApp.Models.AsientosContables", b =>
                {
                    b.Navigation("Detalles");
                });

            modelBuilder.Entity("CooperativaApp.Models.Credito", b =>
                {
                    b.Navigation("Cuotas");
                });

            modelBuilder.Entity("CooperativaApp.Models.Cuota", b =>
                {
                    b.Navigation("Moras");

                    b.Navigation("PagosDetalle");
                });

            modelBuilder.Entity("CooperativaApp.Models.Mora", b =>
                {
                    b.Navigation("Detalles");
                });

            modelBuilder.Entity("CooperativaApp.Models.Parentesco", b =>
                {
                    b.Navigation("Familiaridades");
                });

            modelBuilder.Entity("CooperativaApp.Models.Perfil", b =>
                {
                    b.Navigation("Opciones");
                });

            modelBuilder.Entity("CooperativaApp.Models.Producto", b =>
                {
                    b.Navigation("Tasas");
                });

            modelBuilder.Entity("CooperativaApp.Models.Socio", b =>
                {
                    b.Navigation("HistorialEstados");
                });
#pragma warning restore 612, 618
        }
    }
}
